spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-test?useUnicode=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update